### ISSUE TITLE
Guarantee Treatment Assignment

### ISSUE THREAD

**Issue by michael-butler1994** [manmartgarc/stochatreat#12]
@manmartgarc thank you for creating this useful python package. Quick question: if a treatment block has more than 10 observations, and I want to assign a binary a treatment with 10% probability, at least one observation in the block should be guaranteed treatment, correct? That's how interpret the algorithm McKenzie describes in his blog [post](http://blogs.worldbank.org/impactevaluations/tools-of-the-trade-doing-stratified-randomization-with-uneven-numbers-in-some-strata). 

When I implement stochatreat (version 0.0.8), the condition above does not hold. Here's a crosstab of the dataframe returned by the stochatreat method. I would think stratum 2 should have at least 1 observation assigned to treatment.

![Screenshot 2019-09-23 11 10 34](https://user-images.githubusercontent.com/35438895/65438718-f93fa500-ddf3-11e9-835e-1e0a14dae2ab.png)

**Comment by manmartgarc** [comment]
Hey Michael,

Could you share the code used for this dataframe?

**Comment by michael-butler1994** [comment]
@manmartgarc the attached zipfile has an input data set and a notebook which replicates the bug.
[TreatTest.zip](https://github.com/manmartgarc/stochatreat/files/3642991/TreatTest.zip)

**Comment by manmartgarc** [comment]
Sorry for the delay on the response.

The issue of _guaranteed_ treatment assignment is related the scope of the assignment. By scope I mean if you want to make sure that treatment is randomly and independent _within_ stratum, or _across_ stratum. This is handled by the parameter `misfit_strategy` which defaults to "stratum". 

Running the same code you posted but using the following instead:
```
treats = stochatreat(data=df,
    stratum_cols= ["MinorStrat","R_PerceivedUseStrat"],
    treats=2,
    probs=[9 / 10, 1 / 10],
    idx_col='AppCode',
    random_state=42,
    misfit_strategy='global')

display(pd.crosstab(treats["stratum_id"], treats["treat"], margins=True))
```
returns the following:

```
treat	0	1	All
stratum_id			
0.0	36	4	40
1.0	27	3	30
2.0	9	1	10
3.0	9	1	10
inf	8	1	9
All	89	10	99
```

I have to update the usage section on the main readme file to reflect the implementation of this parameter.

Let me know if this helps.

**Comment by michael-butler1994** [comment]
@manmartgarc thanks for the response! To clarify, the "strata" and "global" ```misfit_strategy``` parameter options correspond to the stata randtreat ```misfits``` parameter options?

**Comment by manmartgarc** [comment]
Yep that is correct.
