### ISSUE TITLE
Rounding error in assignment probabilities

### ISSUE THREAD

**Issue by acarril** [manmartgarc/stochatreat#25]
I noticed that the check for whether the assignment probabilities passed to the `probs` argument is equal to 1 can fail due to a rounding error. As expected, this happens because fractions are converted to floats, which introduces some imprecision. The code excerpt below is where the issue lies:

https://github.com/manmartgarc/stochatreat/blob/38d0e8d087c11178a6dd5ecd7d518527153bf945/src/stochatreat/stochatreat.py#L99-L102

Consider `probs = [1/2, 1/3, 1/6]`. These fractions add up to 1. However, `np.array(probs)` yields `array([0.5       , 0.33333333, 0.16666667])`. Therefore, `np.array(probs).sum()` yields `0.9999999999999999 != 1`.

There are several ways to avoid this issue. For instance, we can use the `Fraction` class from the [`fractions`](https://docs.python.org/3/library/fractions.html) built-in library:

```python
import numpy as np
from fractions import Fraction

probs = [1/2, 1/3, 1/6]
probs_np = np.array(probs)
probs_sum = float(np.array([Fraction(f).limit_denominator() for f in probs]).sum())

probs_sum != 1
>>> False
```

**Comment by manmartgarc** [comment]
Should probably use [math.isclose()](https://docs.python.org/3/library/math.html#math.isclose) for checking this.
